const mongoose = require("mongoose");

const SkillSchema = new mongoose.Schema({
  skillName: { type: String, required: true },
  description: { type: String },
  category: {
    type: String,
    enum: [
      "Art",
      "Programming",
      "Music",
      "Language",
      "Cooking",
      "Fitness",
      "Tutoring",
      "Gardening",
      "Crafts",
      "Photography",
      "Design",
      "Writing",
      "Marketing",
      "Business Consulting",
      "Technical Support",
      "Handyman Services",
      "Health & Wellness",
      "Finance",
      "Legal",
      "Pet Care",
      "Childcare",
      "Home Repair",
      "Beauty & Skincare",
      "Event Planning",
      "Sports Coaching",
      "Travel & Tourism",
      "Culinary Arts",
      "Education",
      "Web Development",
      "Mobile Development",
      "Virtual Assistance",
      "Creative Writing",
      "Other",
    ],
    required: true,
  },
  tradingPreference: {
    type: String,
    enum: ["inPerson", "virtual", "both"],
    required: true,
  },
  value: { type: Number, required: true },
  sampleWorkImage: { type: String },
});

module.exports = mongoose.model("Skill", SkillSchema);
